### ISSUE TITLE
2장 불필요한 맥락 부분 질문 있습니다.

### ISSUE THREAD

**Issue by JuSeong1130** [LetsReadTechBooks/clean-code#1]
1. accountAddress와 customerAddress는 Address 클래스 인스턴스로 좋은 이름이나 클래스 이름으로는 적합하지 못하다.

여기서말하는 클래스의 인스턴스가 뭔지 잘모르겠슴다 혹시 생각하시는 의견있으시면 말씀부탁드립니다.

2. 포트주소,Mac주소를 구분해야한다면 PostalAddress,MAC이라는 이름도 괜찮다. 이렇게하면 의미가 좀더 분명해진다. 

불필요한 맥락이 아닌 Postal이나 MAC은 클래스 이름으로 적절하며 필요한 맥락이라 이해했는데 다른의견 있으실까요

**Comment by aka-nick** [comment]
1. 말 그대로 `Address`의 인스턴스를 말하는 것 같습니다. 
2. 말 그대로 적절한 작명이라는 걸로 받아들였습니다.

정확히 어떤게 궁금하신 건지 이해가 다 된 것 같지 않은데 부가적인 정보가 없어서, 제가 이해한 바를 조금만 더 자세히 남기고 마치겠습니다.
```java
// 예시 1 : GOOD, 어떤 address인지 설명이 필요하다면 변수명으로 알리는 것은 좋은 선택
Address accountAddress = new Address(...);

// 예시 2 : GOOD, 같은 이유로 좋음
Address customerAddress = new Address(...);

// 예시 3 : BAD, AccountAddress에서의 Address(계좌주소)와 CustomerAddress에서의 Address(고객 집주소)가 다른 맥락인데 동일한 어휘로 타입명에 쓰이고 있음
AccountAddress addr1 = new AccountAddress(...);
CustomerAddress addr2 = new CustomerAddress(...);

// 예시 4 : GOOD, 셋 다 '주소'라는 단어로 표현되지만 개념적으로 다르기 때문에 각자의 명칭으로 타입을 명명하는 것이 바람직
PostalAddress postalAddress = new PostalAddress(...);
MAC macAddress = new MAC(...);
URI uriAddress = new URI(...);
```

**Comment by JuSeong1130** [comment]
제가 모르는것에 대해 더 자세하게 설명했어야 했는데 죄송합니다. 좋은 답변 주셔서 감사합니다. 

인스턴스화에 대해 헷갈렸는데 끄적이고 갑니다.
인스턴스화는 추상적인 개념이나 클래스를 실제로 구체적인 객체로 만드는 과정을 의미합니다. 다시 말해, 클래스나 틀을 바탕으로 실제로 사용할 수 있는 개별 객체를 생성하는 것을 인스턴스화라고 합니다.

 
객체란 특정한 개념을 적용할 수 있는 구체적인 사물을 의미한다.
개념이 객체에 적용됐을때 객체를 개념의 인스턴스라고한다.
앨리스가 수만흔 군상들을 단지 트럼프 뿐이라고 일축했던 거처럼
주변의 복잡한 객체들은 몇가지 개념의 인스턴스일 뿐이다.

**Comment by aka-nick** [comment]
해결되셨다면 다행이네요!
질문이 해결될 때는 close with comment로 이슈를 닫아주세용~
이번에는 제가 닫겠습니다~~
