### ISSUE TITLE
3장 오류 코드보다 예외를 사용하라! 의견 부탁드립니다.

### ISSUE THREAD

**Issue by JuSeong1130** [LetsReadTechBooks/clean-code#2]
해당 부분 내용에서 Enum을 변경하게 되면 의존성에 있는 것들이 모두 영향을 받게 된다는것을 보게 되었는데 해당부분에 동감이 되지않아 의견을 구하고자 글올립니다.

Enum보다 Exception을 사용하는게 더 좋다 라고 하는데 비즈니스적인 익셉션을 만들어 사용을해도 익셉션을 바꾼다면 사용하는 모든곳에서 영향을 받게되므로 Exception도 변경에 있어서는 영향을 준다는게 제생각입니다. 생각이 같으시다면 어떻게 생각하시는지 다르시다면 어떤 생각인지 공유해주시면 감사하겠습니다.

**Comment by aka-nick** [comment]
'Exception을 사용하는게 더 좋다'는 저자의 주장에 100% 공감합니다. 하지만 솔직히 말하자면, 저자가 설명하는 이유를 완전히 이해하지 못했습니다.😅  
완전히 이해하지도 못한 내용을 이제와서 다시 리뷰할 수는 없기 때문에(당장 또 해야할 것들이 많기 때문에🥲), 말씀하신 대로, 예외의 변경 가능성 측면에만 집중해서 '개인적인 생각'을 정리 해보겠습니다.  

'반드시 하나의 예외 케이스가 하나의 예외 클래스로 대응'되는 상황이라면 enum과 class 간 별 차이가 없을 수도 있겠다고 생각합니다.  
비즈니스 예외든 구현 예외든, 어떤 Exception도 변경된다면 당연히 관련 코드를 수정해야겠죠. 하지만 수정을 할 때에는 '수정의 여파가 어디까지 미칠까'를 파악하기 쉬워야 좀 더 좋을 거라고 생각합니다.  

Java에서 enum은 class지만 일반적인 class와 다르게 동작하는 부분들이 있습니다.  
예를 들어, enum은 상속 확장 개념이 없습니다. `E_RUNTIME_EXCEPTION`과 `E_ILLEGAL_ARGUMENT_EXCEPTION`이 있다면, 두 enum 간에는 물리적으로 어떤 관계도 없습니다. 한 enum 클래스 안에 있더라도 그냥 같이 있을 뿐이지 두 예외의 관계가 설명되진 않습니다. Java에서는 `RuntimeException`의 하위에 `IllegalArgumentException`이 존재한다는 걸 논리적으로는 알고 있지만, 그건 예외'클래스'일 때만 표현되는 관계입니다.  
다른 예로, 어떤 두 예외 enum `E_BUSINESS_EXCEPTION`과 `E_ILLEGAL_USER_REQUEST`가 있을 경우, 어떤 예외의 여파가 어디까지 미치는지 관련된 코드... 또는 관련되었을 것 같은 코드 전부를 다 살펴보지 않고서는 밝힐 수 없습니다. 

또한 같은 맥락에서, 예외클래스는 다형적으로 구성될 수 있습니다. 하위 예외를 교체하든 추가하든, 상위 예외로 한 번에 처리해두면 굳이 하위 예외의 변경/추가를 일일히 대응할 필요가 없을 수 있습니다. 하지만 새로운 예외를 위하여 예외enum클래스에 새로운 예외enum필드를 추가한다면, 해당 예외를 대응하고 싶다면 `if (지금 발생한 오류가 새로운 예외enum필드와 같은지)`와 같은 코드가 반드시 추가 될 필요가 있습니다. 수정도 마찬가지겠고요.

**Comment by aka-nick** [comment]
작성하고 나서 충분한 시간이 흘렀으므로 읽으신 것으로 간주하고 case closed 하겠습니다 😃
혹여나 다 풀리지 않은 부분이 있다면 다시 이슈를 열어주세요.
