### ISSUE TITLE
9장 단위테스트 - 테스트 당 assert 하나

### ISSUE THREAD

**Issue by aka-nick** [LetsReadTechBooks/clean-code#3]
단위테스트 파트를 재밌게 읽고 있습니다.  
저는 이 파트에서 저자가 '테스트케이스를 작게 유지하는 것이 좋다'고 말하는 것에는 공감이 됩니다. 테스트를 수행할, 프로그래머가 구현한 기능(이하 '기능') 외의 잡다한 코드는 가급적 합치거나 제거하고, 한 테스트 케이스에서 너무 많은 것을 검증해서 뭘 검증하는지 파악하기 어려울 정도로 만들어서는 안된다는 논지로 받아들였어요.  

하지만 `테스트 당 assert 하나` 파트에서 좀 걸리네요. 여기서는 `여러 assert문이 병합되어있는 것이 불합리해보인다(p164 하단)`는 설명과 함께 한 개였던 테스트케이스를 두 개의 테스트 케이스로 나누는 것이 보이는데요.  
저자는 이게 장점이 있다고 하지만 제 생각에는 이렇게 나눠서 얻는 이점보다는 단점이 더 크다고 생각이 들어요.  

나누었을 때 얻을 수 있을 걸로 예상되는 장점은 '깔끔한 테스트 코드'와 '테스트 성공/실패 이유 확인이 명확'하다는 점이에요. 하지만 저는 이 두 가지 이유가 모두 **테스트 코드만을 위한 장점**이 아닌가 생각이 듭니다.  

p164,165의 예제를 보면, 같은 given-when을 사용하고 있음에도(==같은 기능을 테스트하고 있음에도) **확인하고 싶은 테스트 결과 부분**이 다르다는 이유로 단위테스트의 테스트케이스를 쪼개고 있어요. 결과값의 형식이 xml인지, 결과값의 내부에 특정 문자열을 포함하고 있는지를 따로 따로 말이죠.   

이건 오히려 '기능의 정상 동작 확인'이라는 테스트의 주 목적보다는 '깔끔해 보이는 테스트 코드'를 지나치게 강조한 결과가 아닐까요? 사실상 테스트로서의 동작은 똑같게 하고, 가독성의 면에서도 큰 차이가 없는데(심지어 나빠질 수 있다고도 생각합니다), 어째서 assert를 분리해서 확인하라는 걸까요? 심지어 분리한 메소드를 재사용(상속, `@Before` 등...)하려는 목적도 아닌데 말이죠(p165 중반부 참고).  

이쯤 되니 이 파트만큼은 무슨 말을 하는 건지 알아들을 수도 없고 공감도 되지 않는다는 결론이 내려졌습니다.  
혹시 제가 잘못 이해하고 있거나 아직 깨닫지 못한 내용들이 있는 걸까 싶어서 의견을 구해봅니다.

**Comment by aka-nick** [comment]
하나만 첨언하자면, 해당 파트의 마지막 문장에 `하지만 때로는 주저 없이 함수 하나에 여러 assert문을 넣기도 한다. 단지 assert문 개수는 최대한 줄여야 좋다는 생각이다.`라는 말이 있긴 하지만, 이건 저자가 보여준 예시에도 적용되는 문장이라고 생각해요.

**Comment by aka-nick** [comment]
라고 적고 다음 페이지로 넘기니까 바로 다음 파트 첫 문장으로 `어쩌면 "테스트 함수마다 한 개념만 테스트하라"는 규칙이 더 낫겠다.`라는 말이 나오는군요....😇...  
네.. 제가 하고 싶은 말이었고요... 이슈는 바로 닫...지 않고 다양한 의견 들을 수 있도록 며칠만 잠시 열어놓겠습니다.

**Comment by aka-nick** [comment]
의견이 없어 닫습니다 🫥

**Comment by JuSeong1130** [comment]
늦게나마 댓글을 답니다 저도 똑같은부분 음 나도 동감못하는데 하면서 지나갔던 부분이였습니다. 왜냐하면 위에서 말씀하신대로 테스트 함수마다 한개념만 테스트하면된다 생각합니다. 또한  @ParameterizedTest라는 어노테이션을 통해 여러 결과값을 예상하게할 수 있고 이를 통해 assert문을 한개만 쓸 수 있기때문에 많은 신경을 쓰지 않았던거같습니다.
